// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoResizeController from "./auto_resize_controller"
application.register("auto-resize", AutoResizeController)

import CollapseController from "./collapse_controller"
application.register("collapse", CollapseController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)
