default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= Rails.application.credentials.dig(:supabase_database, :dev, :username) %>
  password: <%= Rails.application.credentials.dig(:supabase_database, :dev, :password) %>
  host: <%= Rails.application.credentials.dig(:supabase_database, :dev, :host) %>
  port: <%= Rails.application.credentials.dig(:supabase_database, :dev, :port) %>
  database: <%= Rails.application.credentials.dig(:supabase_database, :dev, :database) %>
  sslmode: require

test:
  <<: *default
  database: RailsTemplateApp_test

production:
  primary: &primary_production
    <<: *default
    username: <%= Rails.application.credentials.dig(:supabase_database, :prod, :username) %>
    password: <%= Rails.application.credentials.dig(:supabase_database, :prod, :password) %>
    host: <%= Rails.application.credentials.dig(:supabase_database, :prod, :host) %>
    port: <%= Rails.application.credentials.dig(:supabase_database, :prod, :port) %>
    database: <%= Rails.application.credentials.dig(:supabase_database, :prod, :database) %>
    sslmode: require
  cache:
    <<: *primary_production
    database: solos_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: solos_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: solos_production_cable
    migrations_paths: db/cable_migrate
